name: Deploy

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '270.0.0'
        service_account_key: ${{ secrets.GCP_SA_KEY }}
    - run: |
        while read -r file; do
        cat $file | bq query --project_id bqfunc --nouse_legacy_sql
        done <<< "$(find udfs -type f -name *.sql)"
