name: zetasqlformat
on: push

jobs:
  zetasqlformat:
    name: zetasqlformat
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          wget https://github.com/Matts966/zetasql-formatter/releases/latest/download/zetasql-formatter_linux_x86_64.zip
          sudo unzip zetasql-formatter_linux_x86_64.zip -d /usr/local/bin
      - name: zetasql-formatter
        run: zetasql-formatter .
